In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import os
import cv2
import numpy as np

DATASET_DIR = "../input/plantvillage-dataset/color"
IMG_SIZE = 64

images = []
labels = []
class_names = sorted(os.listdir(DATASET_DIR))

for label, class_name in enumerate(class_names):
    class_path = os.path.join(DATASET_DIR, class_name)
    
    if not os.path.isdir(class_path):
        continue
    
    for img_name in os.listdir(class_path):
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue
        
        img_path = os.path.join(class_path, img_name)
        img = cv2.imread(img_path)
        
        if img is None:
            continue
        
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img / 255.0
        
        images.append(img)
        labels.append(label)

images = np.array(images)
labels = np.array(labels)

print("Classes:", class_names)
print("Images shape:", images.shape)
print("Labels shape:", labels.shape)


Classes: ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___

In [6]:
np.save("image.npy",images)
np.save("label.npy",labels)

NameError: name 'images' is not defined

In [7]:
path_x="/kaggle/working/image.npy"
path_y="/kaggle/working/label.npy"
X = np.load(path_x)

y=np.load(path_y)

X_flat = X.reshape(X.shape[0], -1)




In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X_flat,y,test_size=0.2,random_state=42)
X_train

array([[0.62352941, 0.61960784, 0.63529412, ..., 0.50588235, 0.50588235,
        0.55294118],
       [0.61960784, 0.6       , 0.65882353, ..., 0.59607843, 0.58431373,
        0.64313725],
       [0.71372549, 0.67843137, 0.72156863, ..., 0.66666667, 0.63529412,
        0.6627451 ],
       ...,
       [0.64313725, 0.6627451 , 0.65882353, ..., 0.42745098, 0.42745098,
        0.42745098],
       [0.65882353, 0.63921569, 0.69803922, ..., 0.47843137, 0.46666667,
        0.52941176],
       [0.3254902 , 0.33333333, 0.33333333, ..., 0.42352941, 0.42352941,
        0.42352941]])

In [10]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

# 1️⃣ Create Dummy Classifier (Most Frequent strategy)
Dummy_Model = DummyClassifier(strategy="most_frequent")

# 2️⃣ Train Dummy Model
Dummy_Model.fit(X_train, y_train)

# 3️⃣ Predict on Test Set
y_pred_dummy = Dummy_Model.predict(X_test)

# 4️⃣ Print Dummy Accuracy
dummy_accuracy = accuracy_score(y_test, y_pred_dummy)
print("Dummy Accuracy:", dummy_accuracy)


Dummy Accuracy: 0.101648098701777


In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Step C: Create & Train Model
My_Model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

My_Model.fit(X_train, y_train)

# Predictions
y_pred = My_Model.predict(X_test)

# Step D: Evaluation
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(cm)


Accuracy: 67.47%
Confusion Matrix:
[[ 25   2   0 ...   2   0  13]
 [  0  64   0 ...   8   0   0]
 [  0   0   0 ...  13   0   2]
 ...
 [  0   0   0 ... 942   0   0]
 [  0   0   0 ...  23   5   3]
 [  0   0   0 ...   5   1 267]]
